# Generated by Django 6.0 on 2026-04-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
