# Generated by Django 6.0 on 2026-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
