# Generated by Django 6.0 on 2026-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products_viewed', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('featured_products_count', models.IntegerField(default=0)),
                ('top_selling_products_count', models.IntegerField(default=0)),
                ('new_arrivals_count', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('active_users_this_week', models.IntegerField(default=0)),
                ('active_users_this_month', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('new_users_this_week', models.IntegerField(default=0)),
                ('new_users_this_month', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('five_star_reviews', models.IntegerField(default=0)),
                ('four_star_reviews', models.IntegerField(default=0)),
                ('three_star_reviews', models.IntegerField(default=0)),
                ('two_star_reviews', models.IntegerField(default=0)),
                ('one_star_reviews', models.IntegerField(default=0)),
                ('verified_reviews', models.IntegerField(default=0)),
                ('total_wishlists', models.IntegerField(default=0)),
                ('total_wishlist_items', models.IntegerField(default=0)),
                ('average_wishlist_size', models.FloatField(default=0.0)),
                ('most_wishlisted_product', models.CharField(blank=True, max_length=255, null=True)),
                ('total_stock_value', models.FloatField(default=0.0)),
                ('out_of_stock_products', models.IntegerField(default=0)),
                ('low_stock_products', models.IntegerField(default=0)),
                ('products_with_zero_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_a_created_a54b18_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('views_today', models.IntegerField(default=0)),
                ('views_this_week', models.IntegerField(default=0)),
                ('views_this_month', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('wishlist_count', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_value', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_views'],
                'indexes': [models.Index(fields=['product_id'], name='analytics_p_product_256442_idx'), models.Index(fields=['total_views'], name='analytics_p_total_v_cfacad_idx')],
            },
        ),
    ]
