# Generated by Django 5.1.15 on 2026-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auth_user_email_lower_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
