from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.core.cache import cache
from django.conf import settings
from .models import Product, ProductImage, ProductSpecification
import logging

logger = logging.getLogger(__name__)

def clear_product_cache(product_id=None):
    """
    Clears the cache for product lists, search, and specific product details.
    IMPORTANT: delete_pattern() with django-redis may not reliably match all keys.
    We explicitly delete known cache keys instead of using wildcards.
    """
    try:
        # Clear specific product-related cache keys
        # These keys are generated by @cache_page decorators and CachedProductSerializer
        cache_keys_to_clear = [
            "product_list",  # From @cache_page on ProductAPIView.get()
            "product_detail",  # From @cache_page on ProductDetailAPIView.get()
            "product_search",
            "analytics",
        ]
        
        for key in cache_keys_to_clear:
            try:
                cache.delete(key)
            except Exception:
                pass  # Silently ignore if key doesn't exist
        
        if product_id:
            # Always clear these specific keys that we know are used
            specific_keys = [
                f"product_images:{product_id}",
                f"product_specs:{product_id}",
                f"product_reviews:{product_id}",
                f"product_inventory:{product_id}",
            ]
            for key in specific_keys:
                try:
                    cache.delete(key)
                except Exception:
                    pass
            
            logger.info(f"Cleared product caches for product_id: {product_id}")
    except Exception as e:
        logger.error(f"Error clearing product cache: {str(e)}")

@receiver(post_save, sender=Product)
def product_saved(sender, instance, **kwargs):
    clear_product_cache(instance.id)
    
    # Manually trigger Elasticsearch sync if enabled
    if getattr(settings, 'USE_ELASTICSEARCH', False):
        try:
            from search.search import ElasticsearchSearchManager
            ElasticsearchSearchManager.index_product(instance)
            logger.info(f"Synced product {instance.id} to Elasticsearch (Save)")
        except Exception as e:
            logger.error(f"Elasticsearch sync failed on save: {str(e)}")

@receiver(post_delete, sender=Product)
def product_deleted(sender, instance, **kwargs):
    clear_product_cache(instance.id)
    
    # Manually trigger Elasticsearch deletion if enabled
    if getattr(settings, 'USE_ELASTICSEARCH', False):
        try:
            from search.search import ElasticsearchSearchManager
            # We use instance.id because the object is still in memory but gone from DB
            ElasticsearchSearchManager.delete_product_index(instance.id)
            logger.info(f"Removed product {instance.id} from Elasticsearch (Delete)")
        except Exception as e:
            logger.error(f"Elasticsearch sync failed on delete: {str(e)}")

@receiver(post_save, sender=ProductImage)
@receiver(post_delete, sender=ProductImage)
def product_image_changed(sender, instance, **kwargs):
    """
    When a ProductImage is added/removed, we need to clear:
    1. Product cache for list views
    2. Specific product cache for that product
    3. Image cache for that product
    This ensures fresh image data is fetched on next request.
    """
    # Clear the general product caches
    clear_product_cache(instance.product_id)
    
    # Force-clear the product list cache since product data changed
    try:
        cache.delete("product_list")
        logger.info(f"Cleared product_list cache due to ProductImage change (product_id={instance.product_id})")
    except Exception as e:
        logger.warning(f"Failed to clear product_list cache: {e}")

@receiver(post_save, sender=ProductSpecification)
@receiver(post_delete, sender=ProductSpecification)
def product_spec_changed(sender, instance, **kwargs):
    clear_product_cache(instance.product_id)
