from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.core.cache import cache
from django.conf import settings
from .models import Product, ProductImage, ProductSpecification
import logging

logger = logging.getLogger(__name__)

def clear_product_cache(product_id=None):
    """
    Clears the cache for product lists, search, and specific product details.
    Uses broader patterns to ensure django-redis matches the keys generated by cache_page.
    """
    try:
        # cache_page keys usually look like: views.decorators.cache.cache_page.product_list.<hash>
        # django-redis prepends the version and KEY_PREFIX, e.g., ecommerce:1:views...
        # Using * prefix ensures we catch them regardless of the internal Django naming.
        cache.delete_pattern("*product_list*")
        cache.delete_pattern("*product_search*")
        
        # Also clear detail caches
        cache.delete_pattern("*product_detail*")
        
        # Clear analytics cache as product counts/data have changed
        cache.delete_pattern("*analytics*")
        
        if product_id:
            # Also clear the custom cached data used in CachedProductSerializer or other places
            cache.delete(f"product_images:{product_id}")
            cache.delete(f"product_specs:{product_id}")
            cache.delete(f"product_reviews:{product_id}")
            cache.delete(f"product_inventory:{product_id}")
            
        logger.info(f"Cleared product caches for product_id: {product_id}")
    except Exception as e:
        logger.error(f"Error clearing product cache: {str(e)}")

@receiver(post_save, sender=Product)
def product_saved(sender, instance, **kwargs):
    clear_product_cache(instance.id)
    
    # Manually trigger Elasticsearch sync if enabled
    if getattr(settings, 'USE_ELASTICSEARCH', False):
        try:
            from search.search import ElasticsearchSearchManager
            ElasticsearchSearchManager.index_product(instance)
            logger.info(f"Synced product {instance.id} to Elasticsearch (Save)")
        except Exception as e:
            logger.error(f"Elasticsearch sync failed on save: {str(e)}")

@receiver(post_delete, sender=Product)
def product_deleted(sender, instance, **kwargs):
    clear_product_cache(instance.id)
    
    # Manually trigger Elasticsearch deletion if enabled
    if getattr(settings, 'USE_ELASTICSEARCH', False):
        try:
            from search.search import ElasticsearchSearchManager
            # We use instance.id because the object is still in memory but gone from DB
            ElasticsearchSearchManager.delete_product_index(instance.id)
            logger.info(f"Removed product {instance.id} from Elasticsearch (Delete)")
        except Exception as e:
            logger.error(f"Elasticsearch sync failed on delete: {str(e)}")

@receiver(post_save, sender=ProductImage)
@receiver(post_delete, sender=ProductImage)
def product_image_changed(sender, instance, **kwargs):
    clear_product_cache(instance.product_id)

@receiver(post_save, sender=ProductSpecification)
@receiver(post_delete, sender=ProductSpecification)
def product_spec_changed(sender, instance, **kwargs):
    clear_product_cache(instance.product_id)
