# Generated by Django 6.0 on 2026-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_frequently_bought_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'subcategory'], name='products_pr_is_acti_973eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'top_selling'], name='products_pr_is_acti_4a0ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'new_arrival'], name='products_pr_is_acti_1d87ce_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='products_pr_is_acti_defdf1_idx'),
        ),
    ]
